stages:
  - static
  - build
static:
  stage: static
  image: python:2.7
  before_script:
    - pip install tox
  script:
    - tox -e flake8,yapf,pylint
build:
  stage: build
  image: python:2.7
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
build3:
  stage: build
  image: python:3.6
  script:
    - rm -rf dist
    - python setup.py sdist bdist_wheel
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
